Normalize more raster types
LayerManager/layman pull request #407
Opened 2021-06-25 20:01 UTC by jirik

Part of issue #167 

- [x] Tests
- ~~Layman Test Client~~
- ~~Changlelog~~
- ~~Documentation~~

2021-06-26 08:02 UTC, index-git requested changes

2021-06-26 08:02 UTC, index-git commented on src/layman/layer/filesystem/tasks.py
> +    if vrt_file_path:
I do not see any value in removing the file. It is not big and can help in problem solving.

2021-07-07 12:47 UTC, jirik commented
News
- description of [get_statistics](https://github.com/LayerManager/layman/pull/407/commits/f3f912a2fe9a78fd416a84d77d14a52c9266e8c8#diff-c58e123e502d37b761d85ff54390ad448d11e832f4116553e744efae1218049aR88)
- new method [is_nodata_ouf_of_min_max](https://github.com/LayerManager/layman/pull/407/commits/d8cab0e22d02799476d57ee34430d4f9ac99f39f)
- new usage of [is_nodata_ouf_of_min_max](https://github.com/LayerManager/layman/pull/407/commits/6f9b5c98d9a4d78bf1d2e333779b6c46ce656e94#diff-c58e123e502d37b761d85ff54390ad448d11e832f4116553e744efae1218049aR127) and [another expected result](https://github.com/LayerManager/layman/pull/407/commits/6f9b5c98d9a4d78bf1d2e333779b6c46ce656e94#diff-8353be2f6bcb8e349126218c7b71847f42f232865feb9c3d1d505db020e6a2acR92)
- new [tested thumbnails](https://github.com/LayerManager/layman/pull/407/commits/644b315a136b0145338125ef2efffe94114f3109)

2021-07-07 15:32 UTC, jirik commented
News
- renamed [is_nodata_out_of_min_max](https://github.com/LayerManager/layman/pull/407/commits/9d8be1fbf213f8cbae19ad2e39774dee57b1419f)
- [rename some tiffs to be more specific](https://github.com/LayerManager/layman/pull/407/commits/19aaa979c6779d2a5cdab495b8088e5609caf4db)
- [add transparent palette with nodata](https://github.com/LayerManager/layman/pull/407/commits/649ae75e756a818f4d10f30ae606cc107b4bc75b) (thumbnail is not tested intentionally - GeoServer does not handle transparency of Paletted image well, I've created issue in Trello)

2021-07-07 16:25 UTC, index-git submitted a review, later dismissed

2021-07-07 19:49 UTC, index-git approved these changes

2021-07-07 20:03 UTC, merged