Improve waiting for task end
LayerManager/layman pull request #540
Opened 2021-12-15 16:56 UTC by index-git

Part of issue #

- [x] Tests
- ~~Layman Test Client~~
- ~~Changlelog~~
- ~~Documentation~~

Optionally
- Add dependency to doc/dependencies.md

2021-12-16 16:47 UTC, jirik requested changes

2021-12-16 16:47 UTC, jirik commented on test_tools/util.py
>  from requests.exceptions import ConnectionError
Try to find some downloadable big file, e.g. in NaturalEarth, and use it instead of africa_surface_lithology.zip

2021-12-16 17:08 UTC, jirik requested changes

2021-12-16 17:08 UTC, jirik commented on src/layman/celery.py
> +        time.sleep(0.3)
0.3 -> 0.5

2021-12-16 17:08 UTC, jirik commented on src/layman/celery.py
> +    max_rounds = 10
10 -> 20

2021-12-16 17:08 UTC, jirik commented on src/layman/celery.py
>              last_task_id = chain_info['last']
Move finish_publication_chain (line 38) after update_related_publications_after_change

2021-12-16 17:08 UTC, jirik commented on src/layman/celery.py
>              finish_publication_chain(last_task_id, task_state)
Move this line after next one

2021-12-16 17:08 UTC, jirik commented on src/layman/celery.py
> +    set_publication_chain_finished(workspace, publication_type, publication_name, state)
Move this line after next one

2021-12-17 15:35 UTC, jirik approved these changes

2021-12-18 16:17 UTC, index-git commented on src/layman/celery.py
> +        finish_publication_chain(task_id, task_state)
finish_publication_chain open the lock, and the "method" on line 45 expects the publication to be unlocked, so this order is needed.

2021-12-20 08:17 UTC, jirik approved these changes

2021-12-20 08:17 UTC, merged