EPSG 4326 axis order test cases
LayerManager/layman pull request #560
Opened 2022-01-07 15:59 UTC by jirik

Part of issue #64

- [x] Tests
- ~~Layman Test Client~~
- ~~Changlelog~~
- ~~Documentation~~

2022-01-10 09:28 UTC, index-git requested changes

2022-01-10 09:28 UTC, index-git commented on tests/dynamic_data/publications/wrong_input.py
> +            'compress': False,
Remove these two lines (compress, with_chunks).

2022-01-11 08:11 UTC, jirik commented on tests/dynamic_data/publications/wrong_input/__init__.py
> +            'file_paths': [f'{os.path.dirname(os.path.abspath(__file__))}/non_readable_raster.tif'],
Optionally use constant for current folder, also for two lines below

2022-01-11 08:11 UTC, jirik commented on tests/dynamic_data/publications/wrong_input/__init__.py
> +                f'{os.path.dirname(os.path.abspath(__file__))}/small_layer_4326_en.shp',
Optionally use constant for current folder

2022-01-11 08:25 UTC, index-git approved these changes

2022-01-11 08:25 UTC, merged