64 vector other crs
LayerManager/layman pull request #566
Opened 2022-01-18 15:48 UTC by index-git

Part of issue #64

- [x] Tests
- ~~Layman Test Client~~
- [x] Changlelog
- [x] Documentation

Optionally
- Add dependency to doc/dependencies.md

2022-01-18 16:47 UTC, jirik requested changes

2022-01-18 16:47 UTC, jirik commented on CHANGELOG.md
> +- [#64](https://github.com/LayerManager/layman/issues/64) Layman supports import of vector layers in "EPSG:5514", "EPSG:32633" and "EPSG:32633".
Rename one  `32633` to `32634`

2022-01-18 16:47 UTC, jirik commented on doc/rest.md
> +- *crs*, string `EPSG:3857`, `EPSG:4326`, `EPSG:5514`, `EPSG:32633` or `EPSG:32633`
Rename one  `32633` to `32634`

2022-01-18 16:47 UTC, jirik commented on doc/rest.md
> +- *crs*, string `EPSG:3857`, `EPSG:4326`, `EPSG:5514`, `EPSG:32633` or `EPSG:32633`
Rename one  `32633` to `32634`

2022-01-18 16:47 UTC, jirik commented on src/crs/__init__.py
> +      <srid>3034</srid>
It should be 900915

2022-01-18 16:47 UTC, jirik commented on src/crs/__init__.py
> +        srid=90015,
It should be 900915

2022-01-18 16:47 UTC, jirik commented on src/crs/__init__.py
> +      <proj4>+proj=lcc +lat_0=52 +lon_0=10 +lat_1=35 +lat_2=65 +x_0=4000000 +y_0=2800000 +ellps=GRS80 +units=m +no_defs</proj4>
Should be same as proj4text below

2022-01-18 16:47 UTC, jirik commented on src/crs/__init__.py
> +        srid=90016,
It should be 900916

2022-01-18 16:47 UTC, jirik commented on src/crs/__init__.py
> +      <srid>3035</srid>
It should be 900916

2022-01-18 16:47 UTC, jirik commented on src/crs/__init__.py
> +      <proj4>+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +units=m +no_defs</proj4>
It should be same as proj4string below

2022-01-18 16:47 UTC, jirik commented on src/crs/__init__.py
> +        qgis_template_spatialrefsys='''<wkt>PROJCRS["ETRS89-extended / LCC Europe",BASEGEOGCRS["ETRS89",DATUM["European Terrestrial Reference System 1989",ELLIPSOID["GRS 1980",6378137,298.257222101,L
Try to update this WKT from epsg.io

2022-01-18 16:47 UTC, jirik commented on src/crs/__init__.py
> +        qgis_template_spatialrefsys='''<wkt>PROJCRS["ETRS89-extended / LAEA Europe",BASEGEOGCRS["ETRS89",DATUM["European Terrestrial Reference System 1989",ELLIPSOID["GRS 1980",6378137,298.257222101,
Try to update this WKT from epsg.io

2022-01-18 17:44 UTC, jirik requested changes

2022-01-18 17:44 UTC, jirik commented on src/crs/__init__.py
> +      <proj4>+proj=lcc +lat_0=52 +lon_0=10 +lat_1=35 +lat_2=65 +x_0=4000000 +y_0=2800000 +ellps=GRS80 +units=m +no_defs</proj4>
I think we should add 3034 to epsg_properties.py

2022-01-18 17:44 UTC, jirik commented on src/crs/__init__.py
> +      <proj4>+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +units=m +no_defs</proj4>
I think we should add 3035 to epsg_properties.py

2022-01-20 16:09 UTC, index-git commented
Replaced by #571 571

2022-01-21 09:43 UTC, closed without merging