Use customized style for grayscale with nodata
LayerManager/layman pull request #654
Opened 2022-09-16 09:02 UTC by jirik

Part of issue #446 

- [x] Tests
- ~~Layman Test Client~~
- [x] Changlelog
- [x] Documentation

2022-09-16 09:17 UTC, index-git requested changes

2022-09-16 09:17 UTC, index-git commented on CHANGELOG.md
> +- [#446](https://github.com/LayerManager/layman/issues/446) If endpoint [POST Workspace Layers](doc/rest.md#post-workspace-layers) receives one-band grayscale input raster file without and if no inpu
Remove `without`

2022-09-16 09:17 UTC, index-git commented on src/layman/layer/geoserver/sld.py
> +    if input_color_interpretations == ['Gray'] and input_mask_flags[0] <= {gdalconst.GMF_ALL_VALID, gdalconst.GMF_NODATA}:
I think  `input_mask_flags[0].issubset({gdalconst.GMF_ALL_VALID, gdalconst.GMF_NODATA})` is readable.

2022-09-21 13:43 UTC, index-git requested changes

2022-09-21 13:43 UTC, index-git commented on src/layman/layer/geoserver/sld.py
> +            nodata_low_entry = f'<sld:ColorMapEntry color="#ffffff" quantity="{nodata_value}" opacity="0" />'
I see it a little bit more intuitive to set `color="#000000"`

2022-09-21 13:43 UTC, index-git commented on tests/dynamic_data/publications/layer_raster_contrast/contrast_test.py
> +    'tif_byte_nodata_low': {},  # nodata < min value
It would be nice to test min_value, max_value and nodata value for these cases during test.

2022-10-13 13:23 UTC, jirik commented
Replaced by #658, #665

2022-10-13 13:23 UTC, closed without merging