Add db_connection param to POST Workspace Layers
LayerManager/layman pull request #734
Opened 2023-01-05 12:19 UTC by index-git

Part of issue #703

- [x] Tests
- [ ] Layman Test Client
- [ ] Changelog
- [ ] Documentation

Optionally
- Add dependency to doc/dependencies.md

2023-01-06 10:22 UTC, jirik requested changes

2023-01-06 10:22 UTC, jirik commented on test_tools/process_client.py
>      # map layers must not be set together with file_paths
```suggestion
```

2023-01-06 10:54 UTC, index-git commented on src/layman/layer/rest_workspace_layers.py
> +        raise LaymanError(1, {
I think, that 1-"Missing parameter" is better.

2023-01-06 12:31 UTC, jirik requested changes

2023-01-06 12:31 UTC, jirik commented on doc/rest.md
> +- save eventual files to workspace directory within Layman data directory
```suggestion
- save files (if sent) to workspace directory within Layman data directory
```

2023-01-06 12:31 UTC, jirik commented on doc/rest.md
> +- for vector layers import eventual vector file to PostgreSQL database as new table into workspace schema
```suggestion
- for vector layers import vector file (if sent) to PostgreSQL database as new table into workspace schema
```

2023-01-06 12:31 UTC, jirik commented on doc/rest.md
> +- *file*, file(s) or file name(s)
```suggestion
- *file*, file(s) or file name(s)
  - exactly one of `file` or `db_connection` must be set
```

2023-01-06 12:31 UTC, jirik commented on doc/rest.md
> +  - is not allowed in combination with *file* parameter
```suggestion
  - exactly one of `file` or `db_connection` must be set
```

2023-01-11 14:30 UTC, jirik requested changes

2023-01-11 14:30 UTC, jirik commented on src/db/util.py
> +    from urllib import parse
Move import up

2023-01-11 14:30 UTC, jirik commented on src/db/util.py
> +        'url': url,
Create new dataclass for connection

2023-01-11 14:30 UTC, jirik commented on src/db/util_test.py
> +    ('', {
Try also:
- ` `
- `_`
- `$^&*(`
- `ščžýžý`

2023-01-11 14:30 UTC, jirik commented on src/db/util.py
> +    connection = parse.urlparse(connection_string, )
Assert that connection.scheme == "postgresql" and that connection.netloc is not empty. Otherwise raise LaymanError

2023-01-12 10:21 UTC, jirik requested changes

2023-01-12 10:22 UTC, jirik approved these changes

2023-01-12 10:53 UTC, merged