528 rewrite wrong input
LayerManager/layman pull request #828
Opened 2023-04-17 13:23 UTC by index-git

Part of issue #528

- [x] Tests
- ~~Layman Test Client (including docker image at docker hub)~~
- ~~Changelog~~
- ~~Documentation~~

2023-04-17 14:20 UTC, jirik requested changes

2023-04-17 14:20 UTC, jirik commented on tests/dynamic_data/publications/wrong_input/wrong_input_test.py
> +        consts.KEY_EXCEPTION: LaymanError,
Use local variable/enum value instead of imported one

2023-04-18 06:46 UTC, index-git commented on tests/dynamic_data/publications/wrong_input/wrong_input_test.py
> +            processing.response.valid_post(workspace=publication.workspace,
We tested only common keys and process_client returns the first item from the response array.

2023-04-18 07:15 UTC, jirik requested changes

2023-04-18 07:15 UTC, jirik commented on tests/dynamic_data/publications/wrong_input/wrong_input_test.py
> +class KEYS(Enum):
KEYS -> Keys

2023-04-18 07:15 UTC, jirik commented on tests/dynamic_data/publications/wrong_input/wrong_input_test.py
> +class KEYS(Enum):
Add unique constraint

2023-04-19 11:47 UTC, jirik approved these changes

2023-04-19 12:13 UTC, merged