893 - Enable to set LOGLEVEL by environment variable
LayerManager/layman pull request #894
Opened 2023-07-25 09:09 UTC by jirik

Part of issue #893

- ~~Tests~~
- ~~Layman Test Client (including docker image at docker hub)~~
- [x] Changelog
- [x] Documentation

2023-07-31 06:36 UTC, index-git requested changes

2023-07-31 06:36 UTC, index-git commented on .env.demo
> +LAYMAN_LOGLEVEL=DEBUG
I expected `INFO` for demo, try it.

2023-07-31 11:44 UTC, index-git approved these changes

2023-08-07 10:04 UTC, jirik commented on .env.demo
> +LAYMAN_LOGLEVEL=INFO
I prefer to keep `DEBUG` for demonstration purposes.

2023-08-07 10:04 UTC, jirik commented on CHANGELOG.md
> +- [#893](https://github.com/LayerManager/layman/issues/893) It is possible to specify logging level by new environment variable [LAYMAN_LOGLEVEL](doc/env-settings.md#LAYMAN_LOGLEVEL). Default level i
Anyway, default value is `DEBUG` if the variable is not set.

2023-08-17 14:17 UTC, index-git requested changes

2023-08-18 10:08 UTC, jirik commented on doc/env-settings.md
> +Logging level. Default value is `DEBUG`, other possible values are `FATAL`, `ERROR`, `WARNING`, and `INFO`.
Default value is `INFO`

2023-08-18 10:09 UTC, jirik commented on doc/env-settings.md
> +Logging level. Default value is `DEBUG`, other possible values are `FATAL`, `ERROR`, `WARNING`, and `INFO`.
```suggestion
Logging level. Default value is `INFO`, other possible values are `FATAL`, `ERROR`, `WARNING`, and `DEBUG`.
```

2023-08-21 06:35 UTC, index-git approved these changes

2023-08-21 06:35 UTC, merged